#!/usr/bin/env python3
"""Generate RT ABI constants from Mesa's canonical vt_rt_abi.h.

Background: Mesa, Spike, and RTL must use identical fixed PDS-header offsets.
Flow: parse Mesa's source-of-truth header and emit checked-in C++ and Scala
      constants for Spike and the RTL.
Usage: python3 tools/rtcore_abi.py [--check]
Maintenance: edit mesa/src/ventus/compiler/vt_rt_abi.h only, then run this
             script and commit both generated outputs.  CI can use --check to
             reject stale generated files.  Pipeline-dependent payload and
             continuation sizes are deliberately not emitted as constants.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "mesa/src/ventus/compiler/vt_rt_abi.h"
SPIKE_OUTPUT = ROOT / "spike/riscv/ventus_rt_abi_generated.h"
SCALA_OUTPUT = ROOT / "gpgpu/ventus/src/rtcore/RtAbiLayout.scala"
DYNAMIC_DEFAULTS = {
    "VT_RT_ABI_HIT_ATTRIB_SIZE_BYTES",
    "VT_RT_ABI_PAYLOAD_BASE_BYTES",
    "VT_RT_ABI_DEFAULT_PAYLOAD_SIZE_BYTES",
    "VT_RT_ABI_REGION_SIZE_BYTES",
}
PAYLOAD_BASE_FUNCTION = "VT_RT_ABI_PAYLOAD_BASE_BYTES_FOR_HIT_ATTRIB_SIZE"


def source_without_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//.*", "", text)


def parse_constants(text: str) -> dict[str, int]:
    text = source_without_comments(text)
    text = re.sub(r"\\\n\s*", " ", text)
    raw: dict[str, str] = {}
    order: list[str] = []

    for name, expression in re.findall(
        r"^\s*#define[ \t]+(VT_RT_[A-Z0-9_]+)[ \t]+([^\r\n]+)$", text, re.MULTILINE
    ):
        if name == "VT_RT_ABI_H":
            continue
        raw[name] = expression.strip()
        order.append(name)

    for body in re.findall(r"enum\s+\w+\s*\{(.*?)\};", text, re.DOTALL):
        current = -1
        for item in body.split(","):
            item = item.strip()
            if not item:
                continue
            match = re.fullmatch(r"(VT_RT_[A-Z0-9_]+)(?:\s*=\s*(.+))?", item)
            if not match:
                raise ValueError(f"cannot parse ABI enum item: {item!r}")
            name, expression = match.groups()
            if expression is None:
                current += 1
            else:
                raw[name] = expression.strip()
                current = resolve_constant(name, raw, {})
            raw[name] = str(current)
            order.append(name)

    resolved: dict[str, int] = {}
    for name in order:
        resolve_constant(name, raw, resolved)
    return {name: resolved[name] for name in order}


def parse_payload_base_function(text: str) -> tuple[str, str]:
    text = source_without_comments(text)
    text = re.sub(r"\\\n\s*", " ", text)
    pattern = (
        rf"^\s*#define[ \t]+{PAYLOAD_BASE_FUNCTION}"
        r"\(([A-Za-z_][A-Za-z0-9_]*)\)[ \t]+([^\r\n]+)$"
    )
    match = re.search(pattern, text, re.MULTILINE)
    if not match:
        raise ValueError(f"missing function-like ABI macro {PAYLOAD_BASE_FUNCTION}")
    return match.group(1), match.group(2).strip()


def resolve_constant(name: str, raw: dict[str, str], resolved: dict[str, int]) -> int:
    if name in resolved:
        return resolved[name]
    if name not in raw:
        raise ValueError(f"unknown ABI constant {name}")

    expression = raw[name]

    def replace_identifier(match: re.Match[str]) -> str:
        identifier = match.group(0)
        return str(resolve_constant(identifier, raw, resolved)) if identifier in raw else identifier

    expression = re.sub(r"\bVT_RT_[A-Z0-9_]+\b", replace_identifier, expression)
    expression = re.sub(r"(?<=\d)[uUlL]+\b", "", expression)
    if not re.fullmatch(r"[0-9xXa-fA-F\s+\-*/%<>&|()~]+", expression):
        raise ValueError(f"unsafe ABI expression for {name}: {expression!r}")
    try:
        value = eval(expression, {"__builtins__": {}}, {})
    except (ArithmeticError, SyntaxError) as error:
        raise ValueError(f"cannot evaluate ABI expression for {name}: {expression!r}") from error
    if not isinstance(value, int):
        raise ValueError(f"non-integer ABI expression for {name}")
    resolved[name] = value
    return value


def cxx_name(name: str) -> str:
    return name.removeprefix("VT_RT_").lower()


def scala_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.removeprefix("VT_RT_").lower().split("_"))


def snake_name(name: str) -> str:
    return re.sub(r"(?<!^)([A-Z])", r"_\1", name).lower()


def lower_camel_name(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def generated_banner(language: str) -> list[str]:
    return [
        f"// Generated by tools/rtcore_abi.py from {SOURCE.relative_to(ROOT)}.",
        "// Do not edit: update the Mesa ABI header and regenerate.",
        f"// {language}",
    ]


def render_spike(constants: dict[str, int], function: tuple[str, str]) -> str:
    argument, expression = function
    cxx_expression = re.sub(r"\bVT_RT_[A-Z0-9_]+\b", lambda m: cxx_name(m.group(0)), expression)
    cxx_argument = snake_name(argument)
    lines = [
        "#ifndef RISCV_VENTUS_RT_ABI_GENERATED_H",
        "#define RISCV_VENTUS_RT_ABI_GENERATED_H",
        *generated_banner("Fixed PDS-header constants for namespace ventus_rt."),
        "",
    ]
    for name, value in constants.items():
        lines.append(f"constexpr reg_t {cxx_name(name)} = {value};")
    lines.extend([
        "",
        f"constexpr reg_t {cxx_name(PAYLOAD_BASE_FUNCTION)}(reg_t {cxx_argument})",
        "{",
        f"  return {cxx_expression};",
        "}",
    ])
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_scala(constants: dict[str, int], function: tuple[str, str]) -> str:
    argument, expression = function
    scala_expression = re.sub(r"\bVT_RT_[A-Z0-9_]+\b", lambda m: scala_name(m.group(0)), expression)
    scala_argument = lower_camel_name(argument)
    scala_expression = re.sub(rf"\b{re.escape(argument)}\b", scala_argument, scala_expression)
    lines = [
        *generated_banner("Fixed PDS-header constants for package rtcore."),
        "package rtcore",
        "",
        "object RtAbiLayout {",
    ]
    for name, value in constants.items():
        lines.append(f"  final val {scala_name(name)}: Int = {value}")
    lines.extend([
        "",
        f"  final def {lower_camel_name(PAYLOAD_BASE_FUNCTION.removeprefix('VT_RT_ABI_').lower())}({scala_argument}: Int): Int =",
        f"    {scala_expression}",
    ])
    lines.extend(["}", ""])
    return "\n".join(lines)


def update_or_check(path: pathlib.Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"stale generated RT ABI file: {path.relative_to(ROOT)}")
        return False
    path.write_text(content, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    try:
        source_text = SOURCE.read_text(encoding="utf-8")
        constants = parse_constants(source_text)
        function = parse_payload_base_function(source_text)
    except (OSError, ValueError) as error:
        print(f"RT ABI generation failed: {error}", file=sys.stderr)
        return 1

    constants = {name: value for name, value in constants.items() if name not in DYNAMIC_DEFAULTS}
    spike_ok = update_or_check(SPIKE_OUTPUT, render_spike(constants, function), args.check)
    scala_ok = update_or_check(SCALA_OUTPUT, render_scala(constants, function), args.check)
    return 0 if spike_ok and scala_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
