name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: humber186/ventus:base-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ventus
        run: ./build-ventus.sh
